jobs:
  test:
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v7
      - name: Install tools
        run: |
          pipx install cpp-coveralls
          sudo apt-get update -y
          sudo apt-get install -y gnu-efi libcmocka-dev lcov mtools ninja-build xorriso
      - name: Configure
        run: cmake -B ${{github.workspace}}/build -G Ninja -DBUILD_TESTS=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}
      - name: Run tests
        run: ctest --test-dir ${{github.workspace}}/build --output-on-failure
      - name: Generate coverage information
        run: |
          geninfo '--exclude=*/tests/*' -b ${{github.workspace}} -o coverage.info \
            ${{github.workspace}}/build/tests/CMakeFiles/test_piece.dir \
            ${{github.workspace}}/build/tests/CMakeFiles/test_game.dir \
            ${{github.workspace}}/build/tests/CMakeFiles/test_font.dir \
            ${{github.workspace}}/build/tests/CMakeFiles/test_render.dir \
            ${{github.workspace}}/build/tests/CMakeFiles/test_main.dir \
            ${{github.workspace}}/build/tests/CMakeFiles/test_loop.dir
      - if: matrix.build-type == 'Debug'
        name: Coveralls
        run: coveralls -i src
    strategy:
      matrix:
        build-type: [Debug, Release]
name: 'Tests'
'on':
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
